name: tests
on: [workflow_dispatch]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 14, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: dmitry-shibanov/setup-node@v-dmshib/add-cache-dependencies-path
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm Install core
        run: npm install
        working-directory: packages/core
        
      - name: npm Install cache
        run: npm install
        working-directory: packages/cache
        
      - name: npm Install artifact
        run: npm install
        working-directory: packages/artifact
        
      - name: npm Install exec
        run: npm install
        working-directory: packages/exec

      - name: npm Install github
        run: npm install
        working-directory: packages/github
        
      - name: npm Install glob
        run: npm install
        working-directory: packages/glob

      - name: npm Install io
        run: npm install
        working-directory: packages/io
        
      - name: npm Install tool-cache
        run: npm install
        working-directory: packages/tool-cache
